apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- tpl ((.Files.Glob "config/*.tmpl").AsConfig) . | nindent 2 }}
